# Generated by Django 5.1.3 on 2024-11-21 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_room_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='tamano',
            field=models.IntegerField(default=0),
        ),
    ]
